"""
Finding Manager
Stores and manages findings generated by the engine.
"""

class FindingManager:

    @staticmethod
    def add(patient, finding):
        patient.findings.add(finding)

    @staticmethod
    def has(patient, finding):
        return finding in patient.findings

    @staticmethod
    def remove(patient, finding):
        patient.findings.discard(finding)

    @staticmethod
    def clear(patient):
        patient.findings.clear()

    @staticmethod
    def display(patient):

        print("\n===== FINDINGS =====")

        if len(patient.findings) == 0:
            print("No findings generated.")
            return

        for finding in sorted(patient.findings):
            print("-", finding)