"""
Finding IDs
Every finding generated by the engine has a unique ID.
"""


# -------------------------
# Bilirubin Findings
# -------------------------

F001 = "Direct Hyperbilirubinemia"
F002 = "Indirect Hyperbilirubinemia"


# -------------------------
# Liver Pattern Findings
# -------------------------

F003 = "Isolated Hyperbilirubinemia"
F004 = "Hepatocellular Pattern"
F005 = "Cholestatic Pattern"


# -------------------------
# Hematology Findings
# -------------------------

F006 = "Anemia"
F007 = "Hemolysis on Peripheral Blood Smear"


# -------------------------
# History Findings
# -------------------------

F008 = "Fever"
F009 = "Dark Urine"
F010 = "Pruritus"
F011 = "Pale Stools"
F012 = "Weight Loss"
F013 = "Alcohol History"
F014 = "Drug History"


# -------------------------
# Examination Findings
# -------------------------

F015 = "Hepatomegaly"
F016 = "Splenomegaly"
F017 = "Tender Hepatomegaly"


# -------------------------
# Imaging Findings
# -------------------------

F018 = "Gallstones on Ultrasound"
F019 = "Dilated CBD on Ultrasound"
F020 = "Pancreatic Head Mass on Ultrasound"